apiVersion: v1
kind: Pod
metadata:
  name: demo-fail
spec:
  hostNetwork: true
  containers:
    - name: app
      image: ghcr.io/example/app:latest
      securityContext:
        runAsNonRoot: false
      ports:
        - containerPort: 8080
          hostPort: 8080
